version: "3.9"

services:
  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    restart: always

  postgres:
    image: postgres:14.1-alpine
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: always

  data-processing:
    build:
      context: .
      dockerfile: dataProcessing.Dockerfile
    volumes:
      - ./pythonCron:/app/output
    env_file: docker.env
    restart: always

  colect-links:
    build:
      context: .
      dockerfile: colectLinks.Dockerfile
    volumes:
      - ./logs:/app/logs
    env_file: docker.env
    restart: always

  colect-data:
    build:
      context: .
      dockerfile: colectData.Dockerfile
    volumes:
      - ./logs:/app/logs
    env_file: docker.env
    restart: always

  teste:
    build:
      context: .
      dockerfile: teste.Dockerfile
    env_file: docker.env
